/* Level 0 web — the rule condition language.
 *
 * Port of level0_rules/operators.py.
 *
 * Rule files are *untrusted data*.  They are shipped by us, edited by
 * consultants and eventually generated by the Level 1 learning loop, so a rule
 * file must never be able to run code.  There is deliberately no eval() and no
 * new Function() anywhere in this application: a condition is a JSON tree,
 * every node is dispatched through the fixed OPERATORS registry below, and an
 * unknown operator is a load-time error rather than a runtime surprise.
 *
 * Every operator also produces *evidence text*.  That is not decoration:
 * section 5.6 requires that no recommendation is ever emitted without the data
 * that supports it, so the evidence is generated by the same code that decides
 * the outcome and cannot drift away from it.
 */
(function (root) {
  'use strict';
  var L0 = (root.Level0 = root.Level0 || {});
  var ds = L0.dataset;
  var fmtNumber = L0.stats.fmtNumber;

  var MAX_CONDITION_DEPTH = 8;
  var MAX_SET_SIZE = 1000;

  function ConditionError(message) {
    var error = new Error(message);
    error.name = 'ConditionError';
    error.isConditionError = true;
    return error;
  }

  /**
   * Outcome of evaluating a condition against one row view.
   *
   * `incomplete` records that a referenced value could not be resolved or
   * coerced.  It is kept separate from `matched` because "we could not check
   * this" and "this is fine" are different statements, and the confidence model
   * penalises the former instead of hiding it.
   *
   * `margin` is the relative overshoot of the strongest matched numeric
   * comparison, and is the effect-size input to the confidence model.
   */
  function ConditionResult(matched, evidence, incomplete, margin) {
    this.matched = !!matched;
    this.evidence = evidence || [];
    this.incomplete = !!incomplete;
    this.margin = margin === undefined ? null : margin;
  }

  /**
   * Namespaced access to the values a condition may reference: `field` (the
   * primary entity row), `alias.field` (a joined row) or `computed.name` (a
   * value the detector derived).  One resolver for all three means the operator
   * set needs no separate cross-table variant of every comparison.
   */
  function RowView(row, namespaces, computed) {
    this.row = row;
    this.namespaces = namespaces || new Map();
    this.computed = computed || new Map();
  }

  RowView.COMPUTED = 'computed';

  /** Return [value, resolvable] for a possibly namespaced field name. */
  RowView.prototype.resolve = function (field) {
    var dot = field.indexOf('.');
    if (dot >= 0) {
      var namespace = field.slice(0, dot);
      var name = field.slice(dot + 1);
      if (namespace === RowView.COMPUTED) {
        if (!this.computed.has(name)) return [null, false];
        return [this.computed.get(name), true];
      }
      if (!this.namespaces.has(namespace)) return [null, false];
      var joined = this.namespaces.get(namespace);
      if (joined === null || joined === undefined) return [null, false];
      var present = ds.hasOwn(joined, name);
      return [present ? joined[name] : null, present];
    }
    var here = ds.hasOwn(this.row, field);
    return [here ? this.row[field] : null, here];
  };

  /** Ambient information some operators need beyond the row itself. */
  function EvalContext(baseline) {
    this.baseline = baseline === undefined ? null : baseline;
  }

  /* ---------------------------------------------------------------- helpers */

  function label(field, value) {
    if (value === null || value === undefined) return field + ' = <missing>';
    if (typeof value === 'string' && ds.isMissing(value)) return field + ' = <missing>';
    if (typeof value === 'number') return field + ' = ' + fmtNumber(value);
    return field + ' = ' + value;
  }

  function numeric(view, field) {
    var resolved = view.resolve(field);
    if (!resolved[1]) return [null, field + ' = <unresolved field>'];
    var value = resolved[0];
    var number = typeof value === 'number' ? value : ds.asFloat(value);
    if (number === null) return [null, label(field, value)];
    return [number, field + ' = ' + fmtNumber(number)];
  }

  /**
   * Coerce to something orderable: a number, or a date as its ordinal, so a
   * single numeric path covers both "lead time > 30" and
   * "actual_ship_date > requested_ship_date".
   */
  function comparable(view, field) {
    var asNumber = numeric(view, field);
    if (asNumber[0] !== null) return asNumber;
    var resolved = view.resolve(field);
    if (resolved[1] && typeof resolved[0] === 'string') {
      var parsed = ds.asDate(resolved[0]);
      if (parsed !== null) return [parsed.toOrdinal(), field + ' = ' + parsed.isoformat()];
    }
    return [null, asNumber[1]];
  }

  /**
   * How far past a threshold a value landed, as a fraction of the threshold.
   * Normalised by max(|threshold|, 1) so a threshold of 0 (perfectly
   * legitimate: "safety stock is 0") does not blow up the effect size.
   */
  function relativeMargin(actual, threshold) {
    return Math.abs(actual - threshold) / Math.max(Math.abs(threshold), 1.0);
  }

  function asText(value, caseSensitive) {
    var text = value === null || value === undefined ? '' : String(value).trim();
    return caseSensitive ? text : text.toLowerCase();
  }

  /* ---------------------------------------------------------------- leaf operators */

  function opMissing(cond, view) {
    var field = cond.field;
    var resolved = view.resolve(field);
    if (!resolved[1]) {
      // An absent *column* is itself a completeness problem, and reporting it
      // as "missing" is more useful than silently skipping the rule.
      return new ConditionResult(true, [field + ' = <column not present in source>'], true);
    }
    var value = resolved[0];
    var text = (typeof value === 'string' || value === null || value === undefined) ? value : String(value);
    return new ConditionResult(ds.isMissing(text), [label(field, value)]);
  }

  function opPresent(cond, view, ctx) {
    var inner = opMissing(cond, view, ctx);
    return new ConditionResult(!inner.matched, inner.evidence, inner.incomplete);
  }

  function opEquals(cond, view) {
    var field = cond.field;
    var caseSensitive = !!cond.case_sensitive;
    var resolved = view.resolve(field);
    if (!resolved[1]) {
      return new ConditionResult(false, [field + ' = <unresolved field>'], true);
    }
    var matched = asText(resolved[0], caseSensitive) === asText(cond.value, caseSensitive);
    return new ConditionResult(matched, [label(field, resolved[0])]);
  }

  function opNotEquals(cond, view, ctx) {
    var inner = opEquals(cond, view, ctx);
    return new ConditionResult(!inner.matched && !inner.incomplete, inner.evidence, inner.incomplete);
  }

  function opInSet(cond, view) {
    var field = cond.field;
    var caseSensitive = !!cond.case_sensitive;
    var resolved = view.resolve(field);
    if (!resolved[1]) {
      return new ConditionResult(false, [field + ' = <unresolved field>'], true);
    }
    var allowed = cond.values.map(function (v) { return asText(v, caseSensitive); });
    var matched = allowed.indexOf(asText(resolved[0], caseSensitive)) >= 0;
    return new ConditionResult(matched, [label(field, resolved[0])]);
  }

  function opNotInSet(cond, view, ctx) {
    var inner = opInSet(cond, view, ctx);
    return new ConditionResult(!inner.matched && !inner.incomplete, inner.evidence, inner.incomplete);
  }

  /**
   * Compare a value against a constant written in the rule.
   *
   * These operators deliberately report NO effect-size margin.  The constant is
   * a policy choice made by the rule author, not an observation, so overshooting
   * it by a factor of ten says something about how the threshold was picked,
   * not about how certain the finding is.
   */
  function makeThresholdOp(symbol, compare) {
    return function (cond, view) {
      var field = cond.field;
      var threshold = Number(cond.value);
      var got = comparable(view, field);
      if (got[0] === null) return new ConditionResult(false, [got[1]], true);
      return new ConditionResult(
        compare(got[0], threshold),
        [got[1] + ' (' + symbol + ' ' + fmtNumber(threshold) + ')']
      );
    };
  }

  /** Compare two values that both come from the data (or from a computation). */
  function makeFieldOp(symbol, compare) {
    return function (cond, view) {
      var leftName = cond.field;
      var rightName = cond.other_field;
      var left = comparable(view, leftName);
      var right = comparable(view, rightName);
      if (left[0] === null || right[0] === null) {
        return new ConditionResult(false, [left[1], right[1]], true);
      }
      var matched = compare(left[0], right[0]);
      // Three separate lines rather than one annotated line, so repeated
      // references to the same value collapse during evidence de-duplication.
      var evidence = [
        left[1],
        right[1],
        leftName + ' ' + symbol + ' ' + rightName + ' is ' + (matched ? 'true' : 'false')
      ];
      return new ConditionResult(matched, evidence, false, matched ? relativeMargin(left[0], right[0]) : null);
    };
  }

  /** field / other_field >= value — a reality gap without hard-coded units. */
  function opRatioGte(cond, view) {
    var leftName = cond.field;
    var rightName = cond.other_field;
    var threshold = Number(cond.value);
    var left = comparable(view, leftName);
    var right = comparable(view, rightName);
    if (left[0] === null || right[0] === null) {
      return new ConditionResult(false, [left[1], right[1]], true);
    }
    if (right[0] === 0) {
      // Dividing by a configured zero is undefined, not "infinitely bad".
      return new ConditionResult(
        false,
        [left[1], right[1], rightName + ' is zero; ratio undefined'],
        true
      );
    }
    var ratio = left[0] / right[0];
    var matched = ratio >= threshold;
    var evidence = [
      left[1],
      right[1],
      'ratio ' + leftName + '/' + rightName + ' = ' + fmtNumber(ratio) +
        ' (threshold ' + fmtNumber(threshold) + ')'
    ];
    var margin = matched ? (ratio - threshold) / Math.max(Math.abs(threshold), 1.0) : null;
    return new ConditionResult(matched, evidence, false, margin);
  }

  /** |field - other_field| >= value: absolute-size guard against noise. */
  function opAbsDiffGte(cond, view) {
    var leftName = cond.field;
    var rightName = cond.other_field;
    var threshold = Number(cond.value);
    var left = comparable(view, leftName);
    var right = comparable(view, rightName);
    if (left[0] === null || right[0] === null) {
      return new ConditionResult(false, [left[1], right[1]], true);
    }
    var diff = Math.abs(left[0] - right[0]);
    var matched = diff >= threshold;
    var evidence = [
      left[1],
      right[1],
      '|' + leftName + ' - ' + rightName + '| = ' + fmtNumber(diff) +
        ' (threshold ' + fmtNumber(threshold) + ')'
    ];
    return new ConditionResult(matched, evidence, false, matched ? relativeMargin(diff, threshold) : null);
  }

  /**
   * Deviation from a baseline computed over the population, in robust sigmas.
   * The baseline is supplied by the detector, never by the rule, so a rule file
   * can never make the engine scan a table it did not declare.
   */
  function opOutlier(cond, view, ctx) {
    var field = cond.field;
    var threshold = Number(cond.value);
    var direction = cond.direction === undefined ? 'both' : String(cond.direction);
    var baseline = ctx.baseline;
    var got = numeric(view, field);
    if (got[0] === null) return new ConditionResult(false, [got[1]], true);
    if (baseline === null || baseline === undefined) {
      return new ConditionResult(false, [got[1], 'no baseline available'], true);
    }
    var score = baseline.robustZ(got[0]);
    if (score === null) {
      return new ConditionResult(false, [got[1], baseline.describe(), 'population has no spread'], true);
    }
    var matched;
    if (direction === 'high') matched = score >= threshold;
    else if (direction === 'low') matched = score <= -threshold;
    else matched = Math.abs(score) >= threshold;
    var evidence = [
      got[1],
      baseline.describe(),
      'robust deviation = ' + fmtNumber(score) + ' sigma (threshold ' + fmtNumber(threshold) +
        ', direction ' + direction + ')'
    ];
    var margin = matched ? relativeMargin(Math.abs(score), threshold) : null;
    return new ConditionResult(matched, evidence, false, margin);
  }

  // name -> [handler, required keys, optional keys]. "op" is implicit.
  var OPERATORS = {
    missing: [opMissing, ['field'], []],
    present: [opPresent, ['field'], []],
    equals: [opEquals, ['field', 'value'], ['case_sensitive']],
    not_equals: [opNotEquals, ['field', 'value'], ['case_sensitive']],
    in_set: [opInSet, ['field', 'values'], ['case_sensitive']],
    not_in_set: [opNotInSet, ['field', 'values'], ['case_sensitive']],
    gt: [makeThresholdOp('>', function (a, b) { return a > b; }), ['field', 'value'], []],
    gte: [makeThresholdOp('>=', function (a, b) { return a >= b; }), ['field', 'value'], []],
    lt: [makeThresholdOp('<', function (a, b) { return a < b; }), ['field', 'value'], []],
    lte: [makeThresholdOp('<=', function (a, b) { return a <= b; }), ['field', 'value'], []],
    field_gt: [makeFieldOp('>', function (a, b) { return a > b; }), ['field', 'other_field'], []],
    field_gte: [makeFieldOp('>=', function (a, b) { return a >= b; }), ['field', 'other_field'], []],
    field_lt: [makeFieldOp('<', function (a, b) { return a < b; }), ['field', 'other_field'], []],
    field_lte: [makeFieldOp('<=', function (a, b) { return a <= b; }), ['field', 'other_field'], []],
    field_equals: [makeFieldOp('==', function (a, b) { return a === b; }), ['field', 'other_field'], []],
    ratio_gte: [opRatioGte, ['field', 'other_field', 'value'], []],
    abs_diff_gte: [opAbsDiffGte, ['field', 'other_field', 'value'], []],
    outlier: [opOutlier, ['field', 'value'], ['direction']]
  };

  var LOGICAL_OPERATORS = ['all', 'any', 'not'];

  /* ---------------------------------------------------------------- evaluation */

  function combineMargin(results) {
    var margins = results
      .map(function (r) { return r.margin; })
      .filter(function (m) { return m !== null && m !== undefined; });
    return margins.length ? Math.max.apply(null, margins) : null;
  }

  function mergeEvidence(results) {
    var evidence = [];
    results.forEach(function (result) {
      result.evidence.forEach(function (item) {
        if (evidence.indexOf(item) < 0) evidence.push(item);
      });
    });
    return evidence;
  }

  function evalAll(condition, view, ctx) {
    var results = condition.conditions.map(function (child) { return evaluate(child, view, ctx); });
    var matched = results.every(function (r) { return r.matched; });
    var incomplete = results.some(function (r) { return r.incomplete; });
    return new ConditionResult(matched, mergeEvidence(results), incomplete, matched ? combineMargin(results) : null);
  }

  function evalAny(condition, view, ctx) {
    var results = condition.conditions.map(function (child) { return evaluate(child, view, ctx); });
    var matched = results.some(function (r) { return r.matched; });
    // Only the satisfied branches are quoted as evidence; listing the branches
    // that did not fire would make the finding harder, not easier, to audit.
    var relevant = matched ? results.filter(function (r) { return r.matched; }) : results;
    var incomplete = relevant.some(function (r) { return r.incomplete; });
    return new ConditionResult(matched, mergeEvidence(relevant), incomplete, matched ? combineMargin(relevant) : null);
  }

  /** Evaluate a validated condition tree against one row view. */
  function evaluate(condition, view, ctx) {
    var context = ctx || new EvalContext();
    var op = condition.op;
    if (op === 'all') return evalAll(condition, view, context);
    if (op === 'any') return evalAny(condition, view, context);
    if (op === 'not') {
      var inner = evaluate(condition.condition, view, context);
      // A negation over an unverifiable value stays unverifiable: flipping
      // "could not check" into "matched" would manufacture false findings.
      return new ConditionResult(!inner.matched && !inner.incomplete, inner.evidence, inner.incomplete);
    }
    var entry = OPERATORS[op];
    if (!entry) throw ConditionError("unknown operator: '" + op + "'");
    return entry[0](condition, view, context);
  }

  /* ---------------------------------------------------------------- validation */

  function ownKeys(object) {
    return Object.keys(object);
  }

  function listText(values) {
    return '[' + values.slice().sort(ds.compareText).map(function (v) { return "'" + v + "'"; }).join(', ') + ']';
  }

  /**
   * Validate a condition tree, throwing ConditionError with a JSON-ish path.
   * Validation happens once at load time so a malformed rule is reported as a
   * rule problem, never as a mid-run crash over customer data.
   */
  function validateCondition(condition, path, depth) {
    var where = path === undefined ? 'condition' : path;
    var level = depth === undefined ? 0 : depth;
    if (level > MAX_CONDITION_DEPTH) {
      throw ConditionError(where + ': condition nested deeper than ' + MAX_CONDITION_DEPTH);
    }
    if (condition === null || typeof condition !== 'object' || Array.isArray(condition)) {
      throw ConditionError(where + ': must be an object');
    }
    var op = condition.op;
    if (typeof op !== 'string') throw ConditionError(where + ": missing string 'op'");

    var extra;
    if (op === 'all' || op === 'any') {
      var children = condition.conditions;
      if (!Array.isArray(children) || !children.length) {
        throw ConditionError(where + ": '" + op + "' requires a non-empty 'conditions' list");
      }
      extra = ownKeys(condition).filter(function (k) { return k !== 'op' && k !== 'conditions'; });
      if (extra.length) {
        throw ConditionError(where + ": unexpected keys for '" + op + "': " + listText(extra));
      }
      children.forEach(function (child, index) {
        validateCondition(child, where + '.conditions[' + index + ']', level + 1);
      });
      return;
    }
    if (op === 'not') {
      if (!('condition' in condition)) throw ConditionError(where + ": 'not' requires 'condition'");
      extra = ownKeys(condition).filter(function (k) { return k !== 'op' && k !== 'condition'; });
      if (extra.length) {
        throw ConditionError(where + ": unexpected keys for 'not': " + listText(extra));
      }
      validateCondition(condition.condition, where + '.condition', level + 1);
      return;
    }

    var spec = OPERATORS[op];
    if (!spec) {
      throw ConditionError(where + ": unknown operator '" + op + "' (known: " +
        Object.keys(OPERATORS).sort(ds.compareText).join(', ') + ')');
    }
    var required = spec[1];
    var optional = spec[2];
    var allowed = ['op'].concat(required, optional);
    var missingKeys = required.filter(function (key) { return !(key in condition); });
    if (missingKeys.length) {
      throw ConditionError(where + ": operator '" + op + "' requires " + listText(missingKeys));
    }
    extra = ownKeys(condition).filter(function (key) { return allowed.indexOf(key) < 0; });
    if (extra.length) {
      throw ConditionError(where + ": unexpected keys for '" + op + "': " + listText(extra));
    }
    ['field', 'other_field'].forEach(function (key) {
      if (key in condition && typeof condition[key] !== 'string') {
        throw ConditionError(where + ": '" + key + "' must be a string");
      }
    });
    if (op === 'in_set' || op === 'not_in_set') {
      var values = condition.values;
      if (!Array.isArray(values) || !values.length) {
        throw ConditionError(where + ": '" + op + "' requires a non-empty 'values' list");
      }
      if (values.length > MAX_SET_SIZE) {
        throw ConditionError(where + ": 'values' exceeds " + MAX_SET_SIZE + ' entries');
      }
      if (values.some(function (v) { return typeof v !== 'string' && typeof v !== 'number'; })) {
        throw ConditionError(where + ": 'values' entries must be scalars");
      }
    }
    if (['gt', 'gte', 'lt', 'lte', 'ratio_gte', 'abs_diff_gte', 'outlier'].indexOf(op) >= 0) {
      if (typeof condition.value !== 'number' || !isFinite(condition.value)) {
        throw ConditionError(where + ": operator '" + op + "' requires a numeric 'value'");
      }
    }
    if ((op === 'equals' || op === 'not_equals') &&
        typeof condition.value !== 'string' && typeof condition.value !== 'number') {
      throw ConditionError(where + ": operator '" + op + "' requires a scalar 'value'");
    }
    if (op === 'outlier') {
      var direction = condition.direction === undefined ? 'both' : condition.direction;
      if (['high', 'low', 'both'].indexOf(direction) < 0) {
        throw ConditionError(where + ": 'direction' must be high, low or both");
      }
    }
  }

  /** Every field name a condition references, for column checks and tests. */
  function conditionFields(condition) {
    var found = [];
    function walk(node) {
      var op = node.op;
      if (op === 'all' || op === 'any') {
        node.conditions.forEach(walk);
        return;
      }
      if (op === 'not') { walk(node.condition); return; }
      ['field', 'other_field'].forEach(function (key) {
        var name = node[key];
        if (typeof name === 'string' && found.indexOf(name) < 0) found.push(name);
      });
    }
    walk(condition);
    return found;
  }

  L0.operators = {
    MAX_CONDITION_DEPTH: MAX_CONDITION_DEPTH,
    MAX_SET_SIZE: MAX_SET_SIZE,
    ConditionError: ConditionError,
    ConditionResult: ConditionResult,
    RowView: RowView,
    EvalContext: EvalContext,
    OPERATORS: OPERATORS,
    LOGICAL_OPERATORS: LOGICAL_OPERATORS,
    evaluate: evaluate,
    validateCondition: validateCondition,
    conditionFields: conditionFields,
    relativeMargin: relativeMargin
  };
})(typeof globalThis !== 'undefined' ? globalThis : this);
